[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
instant_yield_lending = "8yamCrCUweKhUfAhQSyR8pvKUgRcFc2SeuXbLECvkX7i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/tymurt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
